# Generated by Django 4.2.1 on 2023-05-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.CharField(blank=True, max_length=50, null=True)),
                ('imsak', models.TimeField(blank=True, null=True)),
                ('subuh', models.TimeField(blank=True, null=True)),
                ('terbit', models.TimeField(blank=True, null=True)),
                ('duha', models.TimeField(blank=True, null=True)),
                ('zuhur', models.TimeField(blank=True, null=True)),
                ('asar', models.TimeField(blank=True, null=True)),
                ('magrib', models.TimeField(blank=True, null=True)),
                ('iysa', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jadwal',
            },
        ),
    ]
